name = "goodwill-app"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"

[[kv_namespaces]]
binding = "GOODWILL_KV"
id = "fc6dba2cdeb6420c9e0500f1a8643f83"

# Custom domain configuration
[[routes]]
pattern = "api.cdatileandbath.com"
custom_domain = true

# SSL/TLS configuration
[triggers]
crons = ["0 0 * * *"]  # Daily cron job for data updates 

[site]
bucket = "./public" 