name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install backend dependencies
        run: |
          cd Goodwill-app/backend
          npm install

      - name: Install Python dependencies
        run: |
          cd Goodwill-app/backend
          pip install -r requirements.txt

      - name: Migrate data to KV
        run: |
          cd Goodwill-app/backend
          python3 migrate_to_kv.py
          node upload_to_kv.js

      - name: Publish to Cloudflare Workers
        run: |
          cd Goodwill-app/backend
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} 