name: Deploy Worker and Update Data

on:
  push:
    branches:
      - main
  schedule:
    # This will run the workflow automatically every day at 2 AM UTC
    - cron: '0 2 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd Goodwill-app/backend
          npm install
          pip install -r requirements.txt

      - name: Run Full Data Pipeline
        run: |
          cd Goodwill-app/backend
          python3 get_products.py
          python3 gemini.py
          python3 migrate_to_kv.py
        env:
          API_KEY: ${{ secrets.API_KEY }} # Assumes you have a secret named API_KEY for Gemini

      - name: Upload Data to KV Store
        run: |
          cd Goodwill-app/backend
          node upload_to_kv.js
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy Worker
        run: |
          cd Goodwill-app/backend
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }} 